bot:
  token: "8397314478:AAHNXh-vLJh0IlTNHiOVl3dMwB1HgMIpSVw"
  admin_ids: [1063802362]

delivery:
  min_order_amount: 500
  free_delivery_from: 1500
  delivery_cost: 200
  working_hours:
    start: "10:00"
    end: "23:00"

payment:
  methods:
    - cash
    - card_on_delivery
    - online
